package harness

import (
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/tofchaliss/themis-ai-runtime/src/harness/state"

	"github.com/themis-project/themis/internal/kernel/value"
)

// The fixture is a REAL runtime record generated by the harness
// repository's own walk and committed here with provenance (D-I-7).
// Tests reconstruct it; they never edit it. Forged-record tests build
// their own records through the runtime's L6 primitives.

type provenance struct {
	ConstitutionHash string `json:"constitution_hash"`
	AnchorHash       string `json:"anchor_hash"`
	TaskID           string `json:"task_id"`
	ArtifactBoundSeq int64  `json:"artifact_bound_seq"`
	CommissionID     string `json:"commission_id"`
	FindingID        string `json:"finding_id"`
	Skill            string `json:"skill"`
	HarnessCommit    string `json:"harness_commit"`
}

func fixture(t *testing.T) (string, provenance) {
	t.Helper()
	dir, err := filepath.Abs(filepath.Join("testdata", "fixtures", state.ConstitutionHash()[:12]))
	if err != nil {
		t.Fatal(err)
	}
	pb, err := os.ReadFile(filepath.Join(dir, "provenance.json"))
	if err != nil {
		t.Fatalf("no fixture for the compiled runtime constitution %s: %v — regenerate in the harness repository and copy it here", state.ConstitutionHash()[:12], err)
	}
	var p provenance
	if err := json.Unmarshal(pb, &p); err != nil {
		t.Fatal(err)
	}
	if p.ConstitutionHash != state.ConstitutionHash() {
		t.Fatalf("stale fixture: %s vs compiled %s", p.ConstitutionHash, state.ConstitutionHash())
	}
	return dir, p
}

func checkoutFor(dir string) Checkout {
	return Checkout{
		AnchorsRegistryPath:   filepath.Join(dir, "anchors.json"),
		ContractsRegistryPath: filepath.Join(dir, "verification", "contracts.json"),
		HarnessModule:         "github.com/tofchaliss/themis-ai-runtime/src/harness@test",
	}
}

// The witnessing-constitution table must contain the compiled runtime
// constitution (D-W-5 build-time guard) and every entry must re-affirm
// the L8 premise (D-L-3).
func TestWitnessingConstitutionTable(t *testing.T) {
	table := WitnessingConstitutions()
	premises, ok := table[state.ConstitutionHash()]
	if !ok {
		t.Fatalf("compiled runtime constitution %s is not in the witnessing table — Themis has fallen behind a constitution change", state.ConstitutionHash()[:12])
	}
	for h, ps := range table {
		found := false
		for _, p := range ps {
			if p == premiseL8ToolLess {
				found = true
			}
		}
		if !found {
			t.Errorf("constitution %s… does not re-affirm %q", h[:12], premiseL8ToolLess)
		}
	}
	_ = premises
}

// The positive path over the real record: every identity derived,
// five-link witnessed, the commission extracted from CREATED, the
// evidence valid with the derived trust class.
func TestResolveRealRecord(t *testing.T) {
	dir, p := fixture(t)
	root, err := state.OpenRoot(filepath.Join(dir, "state"))
	if err != nil {
		t.Fatal(err)
	}
	ck := checkoutFor(dir)
	r, err := Resolve(root, ck, Tuple{AnchorHash: p.AnchorHash, TaskID: p.TaskID, ArtifactBoundSeq: p.ArtifactBoundSeq})
	if err != nil {
		t.Fatalf("real record refused: %v", err)
	}
	if r.Witness != WitnessL5 || r.L5.SealedSeq == 0 || r.L5.EgressingSeq == 0 || r.L5.EgressOpSeq == 0 {
		t.Fatalf("five-link: witness=%s l5=%+v", r.Witness, r.L5)
	}
	ordered := r.L5.SealedSeq < r.L5.EgressingSeq && r.L5.EgressingSeq < r.L5.EgressOpSeq && r.L5.EgressOpSeq < r.BindingSeq && r.BindingSeq < r.CompletedSeq
	if !ordered {
		t.Fatalf("ordering: %+v binding %d completed %d", r.L5, r.BindingSeq, r.CompletedSeq)
	}
	if r.CommissionID != p.CommissionID || r.Skill != p.Skill || r.VerifiedPath != "report.json" || r.AnchorState != "active" {
		t.Fatalf("derived: commission=%s skill=%s path=%s state=%s", r.CommissionID, r.Skill, r.VerifiedPath, r.AnchorState)
	}
	if len(r.FindingRefs) == 0 || !contains(r.FindingRefs, "ADV-2026-1") {
		t.Fatalf("business refs from the recorded Finding bytes: %v", r.FindingRefs)
	}
	ev, trust := Evidence(r, ck)
	if err := ev.Validate(); err != nil {
		t.Fatalf("evidence: %v", err)
	}
	if trust != value.TrustInferred || ev.Witness != WitnessL5 || ev.Reconstructed != "consistent-pass" || string(ev.CommissionID) != p.CommissionID {
		t.Fatalf("%+v %s", ev, trust)
	}
	if len(r.ModelTurns) == 0 {
		t.Fatal("model turns rendered by identity")
	}
}

// Refusals over the real record, each link-named, with the positive
// twin above.
func TestResolveRefusals(t *testing.T) {
	dir, p := fixture(t)
	root, _ := state.OpenRoot(filepath.Join(dir, "state"))
	ck := checkoutFor(dir)
	good := Tuple{AnchorHash: p.AnchorHash, TaskID: p.TaskID, ArtifactBoundSeq: p.ArtifactBoundSeq}
	must := func(name string, tp Tuple, c Checkout, class error, link string) {
		t.Helper()
		_, err := Resolve(root, c, tp)
		if err == nil || !errors.Is(err, class) || !strings.Contains(err.Error(), link) {
			t.Errorf("%s: %v (want %v … %q)", name, err, class, link)
		}
	}
	other := good
	other.AnchorHash = strings.Repeat("ab", 32)
	must("tuple names another anchor", other, ck, ErrNotReferencable, "the record identifies deployment anchor")
	wrongSeq := good
	wrongSeq.ArtifactBoundSeq = 3
	must("seq is not the binding", wrongSeq, ck, ErrProvenance, "not artifact-bound")
	unknown := good
	unknown.TaskID = "never-ran"
	must("unknown task", unknown, ck, ErrNotReferencable, "unavailable")
	// Anchor never registered on THIS checkout: a registry without it.
	reg := filepath.Join(t.TempDir(), "anchors.json")
	_ = os.WriteFile(reg, []byte(`{"version":1,"kind":"deployment-anchors","entries":[{"name":"other","version":1,"artifact_sha256":"`+strings.Repeat("cd", 32)+`","state":"active"}]}`), 0o644)
	must("anchor not registered here", good, Checkout{AnchorsRegistryPath: reg, ContractsRegistryPath: ck.ContractsRegistryPath}, ErrDeployment, "no longer registered")
	// Contract withdrawn on Themis's checkout: proceeds, state recorded.
	cb, _ := os.ReadFile(ck.ContractsRegistryPath)
	cdir := t.TempDir()
	copyDir(t, filepath.Dir(ck.ContractsRegistryPath), cdir)
	i := strings.LastIndex(string(cb), `"state": "active"`)
	_ = os.WriteFile(filepath.Join(cdir, "contracts.json"), []byte(string(cb)[:i]+`"state": "withdrawn"`+string(cb)[i+len(`"state": "active"`):]), 0o644)
	r, err := Resolve(root, Checkout{AnchorsRegistryPath: ck.AnchorsRegistryPath, ContractsRegistryPath: filepath.Join(cdir, "contracts.json")}, good)
	if err != nil || r.ContractState != "withdrawn" {
		t.Fatalf("contract withdrawn after the fact must proceed with state recorded: %v %+v", err, r)
	}
}

// The historical branch (D-W-5): a record whose constitution is NOT in
// the witnessing table resolves without the L5 links, renders
// l6-record-only, and its evidence is NOT proposal-eligible. Exercised
// by temporarily emptying the table for this process (the table is
// package state; restored after).
func TestHistoricalRecordIsInspectableNotEligible(t *testing.T) {
	dir, p := fixture(t)
	root, _ := state.OpenRoot(filepath.Join(dir, "state"))
	ck := checkoutFor(dir)
	saved := witnessingConstitutions
	witnessingConstitutions = map[string][]string{}
	defer func() { witnessingConstitutions = saved }()
	r, err := Resolve(root, ck, Tuple{AnchorHash: p.AnchorHash, TaskID: p.TaskID, ArtifactBoundSeq: p.ArtifactBoundSeq})
	if err != nil {
		t.Fatalf("historical record must still resolve: %v", err)
	}
	if r.Witness != WitnessL6Only {
		t.Fatalf("witness: %s", r.Witness)
	}
	ev, _ := Evidence(r, ck)
	if err := ev.Validate(); err == nil {
		t.Fatal("an l6-record-only execution must not be proposal-eligible")
	}
}

func contains(ss []string, s string) bool {
	for _, x := range ss {
		if x == s {
			return true
		}
	}
	return false
}

func copyDir(t *testing.T, src, dst string) {
	t.Helper()
	err := filepath.WalkDir(src, func(p string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, _ := filepath.Rel(src, p)
		out := filepath.Join(dst, rel)
		if d.IsDir() {
			return os.MkdirAll(out, 0o755)
		}
		b, err := os.ReadFile(p)
		if err != nil {
			return err
		}
		return os.WriteFile(out, b, 0o644)
	})
	if err != nil {
		t.Fatal(err)
	}
}
