package harness

import (
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"

	"github.com/tofchaliss/themis-ai-runtime/src/harness/state"
)

// The owner's key negative (T-M3), over a REAL record generated by the
// runtime repository: report.json verified (PASS), rewritten, egressed.
// The runtime completed the task; Themis refuses, naming the link.
func TestVerifiedBytesAreNotTheBoundArtifact(t *testing.T) {
	dir, p := fixture(t)
	mdir := dir + "-verify-a-egress-b"
	pb, err := os.ReadFile(filepath.Join(mdir, "provenance.json"))
	if err != nil {
		t.Fatalf("mismatch fixture missing: %v", err)
	}
	var mp provenance
	_ = json.Unmarshal(pb, &mp)
	if mp.ConstitutionHash != p.ConstitutionHash {
		t.Fatalf("mismatch fixture is stale (%s vs %s)", mp.ConstitutionHash[:12], p.ConstitutionHash[:12])
	}
	root, err := state.OpenRoot(filepath.Join(mdir, "state"))
	if err != nil {
		t.Fatal(err)
	}
	_, err = Resolve(root, checkoutFor(mdir), Tuple{AnchorHash: mp.AnchorHash, TaskID: mp.TaskID, ArtifactBoundSeq: mp.ArtifactBoundSeq})
	if err == nil || !errors.Is(err, ErrVerification) || !strings.Contains(err.Error(), "verified bytes are not the bound artifact") {
		t.Fatalf("verify A / egress B must refuse, link-named: %v", err)
	}
}

// Forged records (D-I-7: L6 primitives, never fixtures): a second task
// is built from the real fixture's own objects with ONE alteration. The
// un-altered forge is the positive twin, so each refusal is the
// alteration's. Themis must re-establish, never trust, the record's
// claims.
type forge struct {
	invalidRaw      bool   // PASS claimed over an invalid report; audit and egress agree with the bytes
	auditResultHash string // audit did not produce the raw bytes
	dropEgressOp    bool   // omit the l5-op egress witness
	sealReason      string // seal with another reason
}

func forgeRecord(t *testing.T, dir string, p provenance, task string, f forge) (*state.Root, Tuple) {
	t.Helper()
	src, err := state.OpenRoot(filepath.Join(dir, "state"))
	if err != nil {
		t.Fatal(err)
	}
	evs, err := src.ReadEvents(p.TaskID)
	if err != nil {
		t.Fatal(err)
	}
	man, _ := src.ReadManifest(p.TaskID)
	// A private root: every object the forge cites is copied over so the
	// fixture is never written to.
	rootDir, err := filepath.Abs(t.TempDir())
	if err != nil {
		t.Fatal(err)
	}
	dst, err := state.OpenRoot(rootDir)
	if err != nil {
		t.Fatal(err)
	}
	get := func(id string) []byte {
		b, err := src.Store().GetObject(id)
		if err != nil {
			t.Fatal(err)
		}
		return b
	}
	put := func(class string, b []byte) string {
		id, err := dst.Store().StoreObject(class, b)
		if err != nil {
			t.Fatal(err)
		}
		return id
	}
	var materialized, audit, verif state.Event
	var l5 []state.Event
	for _, e := range evs {
		switch {
		case e.Class == state.EvL2Delivery && strings.Contains(string(e.Body), "materialized-governed-artifacts"):
			materialized = e
		case e.Class == state.EvL4Audit && strings.Contains(string(e.Body), `"Tool":"verify_report"`):
			audit = e
		case e.Class == state.EvVerification:
			verif = e
		case e.Class == state.EvL5Transition || e.Class == state.EvL5Op:
			l5 = append(l5, e)
		}
	}
	for _, r := range materialized.Refs {
		put(r.Class, get(r.ID))
	}
	var vbody struct{ Contract, Outcome, Record string }
	_ = json.Unmarshal(verif.Body, &vbody)
	var record map[string]any
	_ = json.Unmarshal(get(vbody.Record), &record)
	raw := get("sha256:" + record["raw_object_id"].(string))
	var manifest map[string]any
	_ = json.Unmarshal(get(man.ArtifactAddrs[0]), &manifest)
	if f.invalidRaw {
		raw = []byte(`{"finding": "forged", "remediation": "none"}`) // no "evidence"
		record["raw_object_id"] = hexOf(raw)
		ch := manifest["changes"].([]any)[0].(map[string]any)
		ch["content"], ch["new_hash"], ch["size"] = string(raw), hexOf(raw), len(raw)
	}
	var ab map[string]any
	_ = json.Unmarshal(audit.Body, &ab)
	ab["ResultHash"] = hexOf(raw)
	if f.auditResultHash != "" {
		ab["ResultHash"] = f.auditResultHash
	}
	tr, err := dst.CreateTask(task, state.TaskOptions{GovernedHashes: man.GovernedHashes})
	if err != nil {
		t.Fatal(err)
	}
	defer tr.Close()
	if err := tr.Transition(state.StatusRunning, "forged"); err != nil {
		t.Fatal(err)
	}
	if _, err := tr.AppendEvent(materialized.Class, materialized.Writer, materialized.Body, materialized.Refs...); err != nil {
		t.Fatal(err)
	}
	for _, r := range audit.Refs {
		put(r.Class, get(r.ID))
	}
	abody, _ := json.Marshal(ab)
	aev, err := tr.AppendEvent(state.EvL4Audit, "l4", abody, audit.Refs...)
	if err != nil {
		t.Fatal(err)
	}
	record["execution_ref"] = "l4:" + strconv.FormatInt(aev.Seq, 10)
	rb, _ := json.Marshal(record)
	contractID := "sha256:" + record["contract_sha256"].(string)
	canonID := "sha256:" + record["canonical_object_id"].(string)
	put(state.ObjEvidencePayload, get(contractID))
	put(state.ObjEvidencePayload, get(canonID))
	rawID := put(state.ObjEvidencePayload, raw)
	recID := put(state.ObjEvidencePayload, rb)
	refs := []state.Ref{{ID: contractID, Class: state.ObjEvidencePayload}, {ID: rawID, Class: state.ObjEvidencePayload}, {ID: canonID, Class: state.ObjEvidencePayload}, {ID: recID, Class: state.ObjEvidencePayload}}
	vb, _ := json.Marshal(map[string]string{"contract": vbody.Contract, "outcome": vbody.Outcome, "record": recID})
	if _, err := tr.AppendEvent(state.EvVerification, "l10", vb, refs...); err != nil {
		t.Fatal(err)
	}
	manifest["task_id"] = task
	mb, _ := json.Marshal(manifest)
	artID, err := tr.StoreObject(state.ObjEgressArtifact, mb)
	if err != nil {
		t.Fatal(err)
	}
	// The L5 witnesses through the handle (the only path): replay the
	// real record's edges, with the forge's alteration.
	sink := tr.L5Sink()
	for _, e := range l5 {
		if e.Class == state.EvL5Transition {
			var b struct{ From, To, Reason string }
			_ = json.Unmarshal(e.Body, &b)
			if b.To == "SEALED" && f.sealReason != "" {
				b.Reason = f.sealReason
			}
			if b.To == "ACKNOWLEDGED" || b.To == "TEARDOWN" || b.To == "DESTROYED" {
				continue
			}
			if err := sink.Transition(b.From, b.To, b.Reason); err != nil {
				t.Fatal(err)
			}
			continue
		}
		var op map[string]any
		_ = json.Unmarshal(e.Body, &op)
		if op["op"] == "egress" {
			if f.dropEgressOp {
				continue
			}
			if err := sink.Egress("acknowledged", strings.TrimPrefix(artID, "sha256:"), 1, 1); err != nil {
				t.Fatal(err)
			}
			continue
		}
		argv, _ := op["argv"].([]any)
		var as []string
		for _, a := range argv {
			as = append(as, a.(string))
		}
		if err := sink.Op(op["phase"].(string), as, int(op["exit"].(float64)), op["outcome"].(string)); err != nil {
			t.Fatal(err)
		}
	}
	if err := tr.BindArtifact(artID); err != nil {
		t.Fatal(err)
	}
	if err := tr.Transition(state.StatusCompleted, "forged"); err != nil {
		t.Fatal(err)
	}
	evs2, _ := dst.ReadEvents(task)
	var seq int64
	for _, e := range evs2 {
		if e.Class == state.EvArtifact {
			seq = e.Seq
		}
	}
	return dst, Tuple{AnchorHash: p.AnchorHash, TaskID: task, ArtifactBoundSeq: seq}
}

func TestForgedRecordsAreRefused(t *testing.T) {
	dir, p := fixture(t)
	ck := checkoutFor(dir)
	t.Run("positive twin: the un-altered forge is admissible", func(t *testing.T) {
		root, tp := forgeRecord(t, dir, p, "fx-forge-ok", forge{})
		r, err := Resolve(root, ck, tp)
		if err != nil {
			t.Fatalf("fixture: %v", err)
		}
		if r.Witness != WitnessL5 {
			t.Fatalf("witness %s", r.Witness)
		}
	})
	t.Run("PASS claimed over an invalid report", func(t *testing.T) {
		root, tp := forgeRecord(t, dir, p, "fx-forge-claim", forge{invalidRaw: true})
		_, err := Resolve(root, ck, tp)
		if !errors.Is(err, ErrVerification) || !strings.Contains(err.Error(), "reconstruction inconsistent") {
			t.Fatalf("%v", err)
		}
	})
	t.Run("verifier audit did not produce the raw bytes", func(t *testing.T) {
		root, tp := forgeRecord(t, dir, p, "fx-forge-audit", forge{auditResultHash: strings.Repeat("ef", 32)})
		_, err := Resolve(root, ck, tp)
		if !errors.Is(err, ErrVerification) || !strings.Contains(err.Error(), "audit ResultHash") {
			t.Fatalf("%v", err)
		}
	})
	t.Run("egress witness omitted", func(t *testing.T) {
		root, tp := forgeRecord(t, dir, p, "fx-forge-noegress", forge{dropEgressOp: true})
		_, err := Resolve(root, ck, tp)
		if !errors.Is(err, ErrProvenance) || !strings.Contains(err.Error(), "missing l5-op egress witness") {
			t.Fatalf("%v", err)
		}
	})
	t.Run("seal with the wrong reason", func(t *testing.T) {
		root, tp := forgeRecord(t, dir, p, "fx-forge-seal", forge{sealReason: "caller-abort"})
		_, err := Resolve(root, ck, tp)
		if !errors.Is(err, ErrProvenance) || !strings.Contains(err.Error(), "seal reason") {
			t.Fatalf("%v", err)
		}
	})
}
